# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b1564c3813f68db2f8b3304b4ea37d1"
name = "PackageTrack"
handle = "packagetrack"
application_url = "https://omaha-rwanda-query-platforms.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "candystoredev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://omaha-rwanda-query-platforms.trycloudflare.com/auth/callback",
  "https://omaha-rwanda-query-platforms.trycloudflare.com/auth/shopify/callback",
  "https://omaha-rwanda-query-platforms.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
